name:                ast-path
version:             0.2.0
github:              "ijaketak/ast-path"
license:             BSD3
author:              "Keito Kajitani"
maintainer:          "ijaketak@gmail.com"
copyright:           "2019 Keito Kajitani"

category: Data, Natural Language Processing
synopsis: |
  vocabulary representation for predicting program properties
description: |
  Please see the README on GitHub at <https://github.com/ijaketak/ast-path#readme>

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- README.md
- ChangeLog.md

library:
  source-dirs: src

tests:
  ast-path-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-methods
    dependencies:
    - ast-path
    - tasty
    - tasty-hunit
